### CONDOMINIO

GET http://localhost:3000/condominio


### CREATE
POST http://localhost:3000/condominio
content-type: application/json

{
        "cnpj": "94.583.479/0001-28",
        "razaoSocial": "Condomínio Exemplo",
        "email": "josuepayments@gmail.com",
        "senha": "senha123"
}
