### USERS

GET http://localhost:3000/users


### REGISTER

POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Josué Almeida",
    "email": "josuepayments@gmail.com",
    "password": "novasenha123"
    
}

### UPDATE
PUT http://localhost:3000/users/:id
content-type: application/json

{
    "name": "Josué Almeida",
    "email": "josuepayments@gmail.com",
    "password": "novasenha123"
    
}



### GET USERS
GET http://localhost:3000/users/2


### DELETE USERS

DELETE  http://localhost:3000/users/31