### TITULAR
GET http://localhost:3000/titular


### CREATE
POST http://localhost:3000/register/titular
content-type: application/json

{
      "nomeTitular": "Josué Almeida",
      "cpfTitular": "12345678900",
      "Data_Nasc": "01/05/2000",
      "idade": 31,
      "blocoapartamento_id": 1,
      "condominio_id": 7,
      "email": "70043856632@gmail.com",
      "password": "12345678"
     
}

### UPDATE
PUT http://localhost:3000/titular/7
content-type: application/json

{
       "nomeTitular": "Josué Almeida",
      "cpfTitular": "12345678900",
      "Data_Nasc": "01/05/2000",
      "idade": 31,
      "blocoapartamento_id": 1,
      "condominio_id": 7
}


### GET TITULAR
GET http://localhost:3000/titular/1

### DELETE TITULAR
DELETE http://localhost:3000/titular/11

